### ISSUE TITLE
Always convert to DecimalQuantityFormField to str before conversion to Decimal.

### ISSUE THREAD

**Issue by SamuelJennings** [CarliJoy/django-pint#106]
I think we need to change the implementation of the clean method for `DecimalQuantityFormField`. At the moment, a submitted value is passed direct to python's `decimal.Decimal` object, however, for number inputs this can result in unexpected behaviour and confusing user feedback.

For example, if a user submits the value `2.1` to such a field, it will clean to `Decimal('2.100000000000000088817841970012523233890533447265625')` and potentially raise confusing errors depending on the max_digits supplied to the model/form field.

IMO, this is not desirable behaviour and it would make sense to first convert the value to a string in order to preserve precision E.g.

```
>>> from decimal import Decimal
>>> Decimal(2.1)
Decimal('2.100000000000000088817841970012523233890533447265625') # not helpful
>>> Decimal('2.1')
Decimal('2.1') # produces expected result
```

If you agree that this is undesirable behaviour, I think the easiest way to implement would be to specify `DecimalQuantityFormField.to_number_type` and `DecimalQuantityField.to_number_type` as a lambda that converts the value to str before passing it to decimal. Something like,

```
class DecimalQuantityFormField(QuantityFormFieldMixin, forms.DecimalField):
    to_number_type = lambda val: Decimal(str(val))

class DecimalQuantityField(QuantityFieldMixin, models.DecimalField):
    form_field_class = DecimalQuantityFormField
    to_number_type = lambda val: Decimal(str(val))
```

As far as I can tell, nothing else would have to change. Thoughts?

**Comment by CarliJoy** [comment]
Sound reasonable. I agree this is a bug and not only a side effect. 

PR welcome.
Please include a tests that covers this case.
