### ISSUE TITLE
Replace Six

### ISSUE THREAD

**Issue by deanmcginndm** [CarliJoy/django-pint#14]
Hi there,

Please can you replace:
`from django.utils.six import python_2_unicode_compatible`

With:
`from six import python_2_unicode_compatible`

So that this repo will be Py3 compatiable? Seems to work fine but might be worth you testing it properly as Im only using for testing a new project and only need very specific parts of it

**Comment by CarliJoy** [comment]
Dropped Python 2 compatibility with https://github.com/CarliJoy/django-pint/pull/19
