### ISSUE TITLE
Make Widget Works with proper database

### ISSUE THREAD

**Issue by CarliJoy** [CarliJoy/django-pint#25]
After using postgres some test started to fail.
They are all related to comparing pint values and int in widgets.

The branch is called "improve_testing"
@cornelv If you  have time that would be definitely an issue worth looking into!

**Comment by cornelv** [comment]
I looked into this today I wasn't able to figure out the issue I will keep working on this in the following days.

**Comment by CarliJoy** [comment]
I figured it out.
Django called validators for Int fields if a database was used.
