### ISSUE TITLE
Is is possible to just add new definitions to the UnitRegistry

### ISSUE THREAD

**Issue by aabanaag** [CarliJoy/django-pint#33]
I'm trying to in-corporate this to my project but I don't want to specify the whole unitregistry.txt instead I just need to add one or more. (e.g 10000 gallons)

**Comment by CarliJoy** [comment]
See https://pint.readthedocs.io/en/stable/defining.html#programmatically
in `seetings.py` that would translate to:
```
# project/settings.py

from pint import UnitRegistry

# django-pint will set the DJANGO_PINT_UNIT_REGISTER automatically
# as application_registry
DJANGO_PINT_UNIT_REGISTER = UnitRegistry() # Without an argument, it simply loads the default units
DJANGO_PINT_UNIT_REGISTER.define('beer_bootle_weight = 0.8 * kg = beer)

```
