### ISSUE TITLE
Form field base_units is not sent to widget

### ISSUE THREAD

**Issue by cornelv** [CarliJoy/django-pint#4]
I am working on a project where each user can have a default unit set (metric/imperial). This app is perfect for this situation but I found 2 problems:

1. the form field base unit is not passed over to Widget so the select input doesn't have the correct value when the form has initial data
2. when the form has initial data the field value is not converted to the base_units ( it shows the value that is saved in the DB )

**Comment by CarliJoy** [comment]
Fixed with https://github.com/CarliJoy/django-pint/pull/19
