### ISSUE TITLE
error converting small numbers-QuantityWidget decompress scientific notation

### ISSUE THREAD

**Issue by mikeford3** [CarliJoy/django-pint#40]
When converting quantities with small magnitudes defined in the model as a QuantityField the use of scientific notation causes an error in the decompress function in QuantityWidget.

I have a speed quantity with base units of meters per second and a unit choice of inches per second, defined below:

`    alpha = QuantityField(
        verbose_name="Burn Rate Coefficient",
        base_units="m/s", 
        unit_choices=["in/s", "m/s"]
    )
`

When saved to the database with 1 in/s this is correctly displayed in a view as 0.0254 m/s, but when 0.0005079 in/s is used then 1.29006605 m/s is displayed. I think that this is caused in the decompress function, pint converts 0.0005079 in/s to 1.290066e-05 but then the non_decimal.sub("", str(value)) removes the 'e-', leaving 1.29006605. 

I think that the simplest fix might be to change `str(value)` to `"{:f}".format(value)` or fstring equivalent, or just removing the non_decimal call and erroring if value cannot be converted to a number.

**Comment by CarliJoy** [comment]
Thanks for figuring it out and suggesting a PR.
I looked into the root of the problem and I think I found it.

It should now work as expected.

**Comment by CarliJoy** [comment]
If not please reopen the issue.
