### ISSUE TITLE
Can't save empty value if the field is not required

### ISSUE THREAD

**Issue by cornelv** [CarliJoy/django-pint#7]
If the form field is not required and an empty value is sent it throws and exception in quantityfield/fields.py in clean, line 118: Value error: could not convert string to float

**Comment by CarliJoy** [comment]
Will have  look into it.

**Comment by CarliJoy** [comment]
I tried with:
https://github.com/CarliJoy/django_pint_example
and can't reproduce the issue.
But I also remembered that I used the definition of the the float field from django.
So I guess it is fixed properly ;-)

**Comment by cornelv** [comment]
Thanks for the update, I appreciate that you are looking into these issues.  
Thank you for your hard work.
