### ISSUE TITLE
Specify unit choices in model field declaration

### ISSUE THREAD

**Issue by rgov** [CarliJoy/django-pint#9]
I see that I can add a `QuantityField` to my model, for instance, `quantity = QuantityField('mL')`, but then in the admin form I only get the one 'mL' option in the popup.

It would be nice to be able to set `choices=['floz', 'mL', 'quart']` on the model declaration and have that propagated to the form field.

As it is, I'm not sure what I have to do—write a custom form that specifies the a `QuantityFormField` with the appropriate `unit_choices`?

**Comment by CarliJoy** [comment]
With the current version you can now define `unit_choices` directly in the model field defintion.
I explicitly did not use the choices argument as I guess there could be further use cases that that require something like this:
`QuantitfyField("meter", choices=[10,20,30], unit_choices=["milimeter"])`
Where as it has to be defined what this means (like choices of 10m 10mm?)

BR

Carli*
