### ISSUE TITLE
pint context

### ISSUE THREAD

**Issue by mmarras** [CarliJoy/django-pint#99]
Is there a(lready) way to use the QuanityField with a pint [context](https://pint.readthedocs.io/en/stable/user/contexts.html)? 

An example of what I would like to do (note the units for force [Newtons] and weight [kilogram] occuring together which makes sense on earth): 
```python
class Model(models.model):
    with ureg.context('earth'):
        field = QuantityField(base_unit='N', default = ureg.Quantity(1,'kg'), unit_choices=['kN', 'ton'])
```

**Comment by mmarras** [comment]
`check_matching_unit_dimension` uses a very rigid definition of matching dimensions by checking dimensionality which will never take more sophisticated conversions into account [An example, on earth, a weight is also always associated with a corresponding force by 9.81m/s**2 acceleration constant (neglective that it's a function of height)]. Changing this to literally testing if units can be converted allows you to use `with ureg.context('earth')` scopes during `QuantityField` definition. Still have to investigate, if we need further modifications when data is loaded from the db. But the below proposed solution is imho also more in line with the python principle of 'if it quacks like a duck it is a duck'.

```
from pint import DimensionalityError, UnitRegistry
from typing import List


def check_matching_unit_dimension(
    ureg: UnitRegistry, base_units: str, units_to_check: List[str]
) -> None:
    """
    Check if all units_to_check have the same Dimension like the base_units
    If not
    :raise DimensionalityError
    """

    base_unit = getattr(ureg, base_units)

    base_quant = 1 * base_unit
    
    for unit_string in units_to_check:
        unit = getattr(ureg, unit_string)
        try: 
            base_quant.to(unit)
        except DimensionalityError:
            raise DimensionalityError(base_unit, unit)

```

**Comment by mmarras** [comment]
I had some issues, because I also use the [django simple history extension](https://pypi.org/project/django-simple-history/), but if you can globally set your context: `ureg.enable_contexts("earth")`, with the above modification it seems to work. 

Do you want me to put a PR for the change above or rather do that yourself?

**Comment by CarliJoy** [comment]
Hi, thank you for your issue.
I didn't know the feature existed.

A PR including test is welcome :-)
